// src/lib/route-map.ts
export const ROUTE_TITLES: Record<string, string> = {
  "/appointment/:appointmentId": "Details",
  "/booking": "",
  "/booking/dateTime": "",
  "/booking/review": "",
  "/booking/service": "",
  "/booking/staff": "",
  "/checkin/:appointmentId": "Check-In",
  "/dashboard": "",
  "/discover/barbers": "Descubre Talento",
  "/discover/stores": "Descubre Tiendas",
  "/history": "",
  "/pool": "",
  "/profile": "",
  "/profile/edit": "Edit",
  "/qr": "",
  "/stores": "",
  "/stores/:storeId": "Store Details",
  "/welcome": "",
};
